require "bigdecimal"

module DfeRb
  module Nfe
    # Official tables shipped with the gem (data/, regenerated by script/update_tables):
    # IBGE city codes and the IBS/CBS tax classifications (cClassTrib, IT 2025.002).
    # Loaded on first use.
    module Tables
      DATA = File.expand_path("data", __dir__)

      # One cClassTrib row: its CST, the rate reductions in percent and the CST's indicators.
      Classification = Struct.new(:code, :cst, :ibs_reduction, :cbs_reduction, :taxed, :rate_reduction, :monophase,
        :valid_from, :valid_until) do
        def taxed? = taxed
        def rate_reduction? = rate_reduction
        def monophase? = monophase
      end

      module_function

      # "Campo Grande" for "5002704", or nil.
      def city_name(code) = cities[code.to_s]

      # The IBGE code of the city called `name` in `state`, ignoring case and accents, or nil.
      def city_code(name, state)
        prefix = States.code(state)
        city_codes[[prefix, fold(name)]]
      rescue ArgumentError
        nil
      end

      # The Classification for a cClassTrib code, or nil.
      def classification(code) = classifications[code.to_s]

      def fold(text)
        text.to_s.unicode_normalize(:nfkd).gsub(/\p{Mn}/, "").downcase.gsub(/[^a-z0-9]+/, " ").strip
      end

      def cities
        @cities ||= rows("municipalities.tsv").to_h.freeze
      end

      def city_codes
        @city_codes ||= cities.to_h { |code, name| [[code[0, 2], fold(name)], code] }.freeze
      end

      def classifications
        @classifications ||= rows("classifications.tsv").drop(1).to_h do |code, cst, ibs, cbs, taxed, reduction, mono, from, to|
          [code, Classification.new(code: code, cst: cst, ibs_reduction: BigDecimal(ibs), cbs_reduction: BigDecimal(cbs),
            taxed: taxed == "1", rate_reduction: reduction == "1", monophase: mono == "1", valid_from: from,
            valid_until: to.to_s.empty? ? nil : to).freeze]
        end.freeze
      end

      def rows(file)
        File.readlines(File.join(DATA, file), chomp: true, encoding: "UTF-8").map { |line| line.split("\t", -1) }
      end
    end
  end
end
