require "bigdecimal"
require "date"

module DfeRb
  module Nfe
    # Official tables shipped with the gem (data/, regenerated by script/update_tables):
    # IBGE city codes, the IBS/CBS tax classifications (cClassTrib, IT 2025.002), the CFOP
    # table (IT 2023.002), the TIPI's IPI rates (Decreto 11.158/2022 and its updates) and the
    # payment methods and card brands (tPag of IT 2024.002, tBand). Loaded on first use.
    module Tables
      DATA = File.expand_path("data", __dir__)

      # One cClassTrib row: its CST, the rate reductions in percent, the CST's indicators and
      # whether it calls for the regular taxation group (ind_gTribRegular).
      Classification = Struct.new(:code, :cst, :ibs_reduction, :cbs_reduction, :taxed, :rate_reduction, :monophase,
        :deferral, :regular_taxation, :valid_from, :valid_until) do
        def taxed? = taxed
        def rate_reduction? = rate_reduction
        def monophase? = monophase
        def deferral? = deferral
        def regular_taxation? = regular_taxation
      end

      # One CFOP row: its validity and the indicators the validation rules consult (indNFe,
      # indComunica, indTransp, indDevol, indRetor, indAnula, indRemes, indComb,
      # indExcIBSCBS). `fuel` is indComb: 0, 1 (fuel group required) or 2 (carrier too).
      # Direction and scope come from the first digit: 1-3 entries, 5-7 exits; 1/5 within
      # the state, 2/6 interstate, 3/7 foreign.
      Cfop = Struct.new(:code, :valid_from, :valid_until, :nfe, :communication, :transport, :devolution, :goods_return,
        :annulment, :remittance, :fuel, :ibs_cbs_only, :title) do
        def nfe? = nfe
        def communication? = communication
        def transport? = transport
        def devolution? = devolution
        def goods_return? = goods_return
        def annulment? = annulment
        def remittance? = remittance
        def fuel? = fuel.positive?
        def ibs_cbs_only? = ibs_cbs_only
        def entry? = code.to_i < 5000
        def exit? = !entry?
        def scope = CFOP_SCOPES[code.to_i / 1000 % 4]

        # Whether the code is in force on `date` (a Date, a Time or "yyyy-mm-dd"). The end date
        # is the first day it is no longer accepted, so it is excluded (IT 2023.002).
        def valid_on?(date = Date.today)
          day = date.respond_to?(:strftime) ? date.strftime("%F") : date.to_s[0, 10]
          valid_from <= day && (valid_until.nil? || day < valid_until)
        end
      end
      CFOP_SCOPES = {1 => :internal, 2 => :interstate, 3 => :foreign}.freeze

      # One TIPI line: an 8-digit NCM, or one of its EX exceptions (EXTIPI), with the IPI
      # rate in percent. A line the table marks NT is not taxed and has no rate.
      IpiRate = Struct.new(:ncm, :ex, :rate, :non_taxed) do
        def non_taxed? = non_taxed
      end

      # One payment method (tPag): its title and the first day it is accepted, nil for the
      # codes the table started with.
      PaymentMethod = Struct.new(:code, :title, :valid_from) do
        # True for 90 (sem pagamento) and 91 (pagamento posterior), which aren't paid at issue,
        # so their vPag is 0.00 (RV YA03-30).
        def deferred? = DEFERRED_PAYMENTS.include?(code)

        # Whether the code is accepted on `date` (a Date, a Time or "yyyy-mm-dd").
        def valid_on?(date = Date.today)
          day = date.respond_to?(:strftime) ? date.strftime("%F") : date.to_s[0, 10]
          valid_from.nil? || valid_from <= day
        end
      end
      DEFERRED_PAYMENTS = %w[90 91].freeze

      module_function

      # "Campo Grande" for "5002704", or nil.
      def city_name(code) = cities[code.to_s]

      # The IBGE code of the city called `name` in `state`, ignoring case and accents, or nil.
      def city_code(name, state)
        prefix = States.code(state)
        city_codes[[prefix, fold(name)]]
      rescue ArgumentError
        nil
      end

      # The Classification for a cClassTrib code, or nil.
      def classification(code) = classifications[code.to_s]

      # The Cfop for a code ("5102", "5.102" or 5102), or nil.
      def cfop(code) = cfop_index[code.to_s.delete(".")]

      # Every Cfop, by code. With `matching:`, those whose title has every word of it,
      # ignoring case and accents, and whose code starts with its numbers ("remessa conserto",
      # "6.9 retorno").
      def cfops(matching: nil)
        return cfop_index.values if matching.nil?

        numbers, words = fold(matching.to_s.delete(".")).split.partition { |word| word.match?(/\A\d+\z/) }
        cfop_index.values.select do |row|
          title = fold(row.title)
          numbers.all? { |number| row.code.start_with?(number) } && words.all? { |word| title.include?(word) }
        end
      end

      # The IpiRate of an NCM ("22030000" or "2203.00.00"): the line of its EX (EXTIPI, "01"
      # or "1") when one is given and the TIPI lists it, else the NCM's own. Nil when the TIPI
      # lacks the NCM.
      def ipi_rate(ncm, ex = nil)
        ncm = ncm.to_s.delete(".")
        ex = ex.to_s.strip.sub(/\A0+(?=\d)/, "")
        (ipi_index[[ncm, ex]] unless ex.empty?) || ipi_index[[ncm, nil]]
      end

      def ipi_rates = ipi_index.values

      # The PaymentMethod for a tPag ("17" or 17), or nil.
      def payment_method(code) = payment_index[code.to_s.rjust(2, "0")]

      def payment_methods = payment_index.values

      # Card brand names by tBand: {"01" => "Visa", ...}.
      def card_brands
        @card_brands ||= rows("card_brands.tsv").drop(1).to_h.freeze
      end

      def fold(text)
        text.to_s.unicode_normalize(:nfkd).gsub(/\p{Mn}/, "").downcase.gsub(/[^a-z0-9]+/, " ").strip
      end

      def cities
        @cities ||= rows("municipalities.tsv").to_h.freeze
      end

      def city_codes
        @city_codes ||= cities.to_h { |code, name| [[code[0, 2], fold(name)], code] }.freeze
      end

      def classifications
        @classifications ||= rows("classifications.tsv").drop(1).to_h do |code, cst, ibs, cbs, taxed, reduction, mono, dif, regular, from, to|
          [code, Classification.new(code: code, cst: cst, ibs_reduction: BigDecimal(ibs), cbs_reduction: BigDecimal(cbs),
            taxed: taxed == "1", rate_reduction: reduction == "1", monophase: mono == "1", deferral: dif == "1",
            regular_taxation: regular == "1", valid_from: from, valid_until: to.to_s.empty? ? nil : to).freeze]
        end.freeze
      end

      def cfop_index
        @cfop_index ||= rows("cfop.tsv").drop(1).to_h do |code, from, to, nfe, communication, transport, devolution, goods_return, annulment, remittance, fuel, ibs_cbs_only, title|
          [code, Cfop.new(code: code, valid_from: from, valid_until: to.empty? ? nil : to, nfe: nfe == "1",
            communication: communication == "1", transport: transport == "1", devolution: devolution == "1",
            goods_return: goods_return == "1", annulment: annulment == "1", remittance: remittance == "1",
            fuel: Integer(fuel), ibs_cbs_only: ibs_cbs_only == "1", title: title).freeze]
        end.freeze
      end

      def ipi_index
        @ipi_index ||= rows("tipi.tsv").drop(1).to_h do |ncm, ex, rate|
          ex = nil if ex.empty?
          [[ncm, ex], IpiRate.new(ncm: ncm, ex: ex, rate: (BigDecimal(rate) unless rate == "NT"), non_taxed: rate == "NT").freeze]
        end.freeze
      end

      def payment_index
        @payment_index ||= rows("payment_methods.tsv").drop(1).to_h do |code, from, title|
          [code, PaymentMethod.new(code: code, title: title, valid_from: from.empty? ? nil : from).freeze]
        end.freeze
      end

      def rows(file)
        File.readlines(File.join(DATA, file), chomp: true, encoding: "UTF-8").map { |line| line.split("\t", -1) }
      end
    end
  end
end
